import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="/sc.js"></Script>

      <main
        className={`flex min-h-screen flex-col items-center justify-between p-2 ${inter.className}`}
      >
        <nav class="p-4 py-">
          <div class="container mx-auto">
            <div class="flex items-center justify-between">
              <div class="text-white font-semibold text-lg px-4">

              </div>
              <ul class="flex space-x-5">
                <li>
                  <a href="#" class="text-white hover:text-gray-300">
                    Home
                  </a>
                </li>
                <li>
                  <a href="#" class="text-white hover:text-gray-300">
                    About
                  </a>
                </li>
                <li>
                  <a href="#" class="text-white hover:text-gray-300">
                    Blog
                  </a>
                </li>
                <li>
                  <a href="#" class="text-white hover:text-gray-300">
                    Notes
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
      </main>
    </div>
  );
}
